import 'package:project/Modules/estacoes.dart';

List<Estacoes> estacoes = [
  Estacoes(
    endereco:
        'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
    estrela: 1,
    kwh: '1,25',
    kwhint: 1.25,
    latitude: 52,
    longitude: 555555,
    nome: 'POSTO NAIKA',
    salvo: true,
  ),
  Estacoes(
    endereco: 'Av. Dom Hélder Câmara, 2',
    estrela: 2,
    kwh: '1,35',
    kwhint: 1.35,
    latitude: 555,
    longitude: 555555,
    nome: 'POSTO NAIKA',
    salvo: false,
  ),
  Estacoes(
    endereco: 'Av. Dom Hélder Câmara, 3',
    estrela: 3,
    kwh: '1,45',
    kwhint: 1.45,
    latitude: 5555,
    longitude: 55555,
    nome: 'POSTO NAIKA',
    salvo: false,
  ),
  Estacoes(
    endereco: 'Av. Dom Hélder Câmara, 4',
    estrela: 4,
    kwh: '1,55',
    kwhint: 1.55,
    latitude: 555555,
    longitude: 55555,
    nome: 'POSTO NAIKA',
    salvo: false,
  ),
  Estacoes(
    endereco: 'Av. Dom Hélder Câmara, 5',
    estrela: 5,
    kwh: '1,65',
    kwhint: 1.65,
    latitude: 555555,
    longitude: 55555,
    nome: 'POSTO SHELL',
    salvo: true,
  ),
  Estacoes(
    endereco: 'Av. Dom Hélder Câmara, 6',
    estrela: 5,
    kwh: '1,75',
    kwhint: 1.75,
    latitude: 55555,
    longitude: 55555,
    nome: 'POSTO SHELL',
    salvo: false,
  ),
];
