import 'package:project/Modules/posto.dart';

List<Posto> posto = [
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 1,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 1,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 1,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 1,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 1,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
  Posto(
      endereco:
          'Alameda Joaquim Eugênio de Lima, 238 - Jardim Paulista, São Paulo - SP',
      estrela: 2,
      latitude: 52,
      longitude: 555555,
      nome: 'POSTO NAIKA',
      salvo: true,
      gasolina: '1,25',
      gasolinaaditivada: '1,25',
      gas: '1,25',
      alcool: '1,25',
      alcoolint: 1.25,
      gasint: 1.25,
      gasolinaaditivadaint: 1.25,
      gasolinaint: 1.25),
];
