// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUh95he7kXVUC6wnh0mTlOrLdshpStAk',
    appId: '1:700211734358:web:9717bcd36143a2903d98f7',
    messagingSenderId: '700211734358',
    projectId: 'no-transito',
    authDomain: 'no-transito.firebaseapp.com',
    databaseURL: 'https://no-transito-default-rtdb.firebaseio.com',
    storageBucket: 'no-transito.appspot.com',
    measurementId: 'G-FCKM3GX33M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz7BMtakz1WBxjQCstRi_vfcmnUnALaAw',
    appId: '1:700211734358:android:7a1c10e7bc810a193d98f7',
    messagingSenderId: '700211734358',
    projectId: 'no-transito',
    databaseURL: 'https://no-transito-default-rtdb.firebaseio.com',
    storageBucket: 'no-transito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnemBuuzYOH9jWy_WnGfue-cdMKco9F5M',
    appId: '1:700211734358:ios:fbcdbb6dd5b9c1d53d98f7',
    messagingSenderId: '700211734358',
    projectId: 'no-transito',
    databaseURL: 'https://no-transito-default-rtdb.firebaseio.com',
    storageBucket: 'no-transito.appspot.com',
    iosClientId: '700211734358-f848q2j4a13o6kps16ugracgthghvltl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnemBuuzYOH9jWy_WnGfue-cdMKco9F5M',
    appId: '1:700211734358:ios:fbcdbb6dd5b9c1d53d98f7',
    messagingSenderId: '700211734358',
    projectId: 'no-transito',
    databaseURL: 'https://no-transito-default-rtdb.firebaseio.com',
    storageBucket: 'no-transito.appspot.com',
    iosClientId: '700211734358-f848q2j4a13o6kps16ugracgthghvltl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
